domain_path: C:\Users\Alejandro\Documents\git\vitis_Urbana_2024_1\genesys2\export\genesys2\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
