#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_0_IS_DUAL 0x1
#define XPAR_AXI_GPIO_0_INTERRUPTS 0x2001
#define XPAR_FABRIC_AXI_GPIO_0_INTR 1
#define XPAR_AXI_GPIO_0_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_FABRIC_XGPIO_0_INTR 1
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x8
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_0_IS_DUAL 0x1
#define XPAR_XGPIO_0_INTERRUPTS 0x2001
#define XPAR_XGPIO_0_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral AXI_GPIO_1 */
#define XPAR_AXI_GPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_1_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_1_HIGHADDR 0x4001ffff
#define XPAR_AXI_GPIO_1_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_1_IS_DUAL 0x0
#define XPAR_AXI_GPIO_1_INTERRUPTS 0x2000
#define XPAR_FABRIC_AXI_GPIO_1_INTR 0
#define XPAR_AXI_GPIO_1_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_1_GPIO_WIDTH 0x5

/* Canonical definitions for peripheral AXI_GPIO_1 */
#define XPAR_XGPIO_1_BASEADDR 0x40010000
#define XPAR_FABRIC_XGPIO_1_INTR 0
#define XPAR_XGPIO_1_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x5
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_1_IS_DUAL 0x0
#define XPAR_XGPIO_1_INTERRUPTS 0x2000
#define XPAR_XGPIO_1_INTERRUPT_PARENT 0x41200001

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_INTC_0 */
#define XPAR_AXI_INTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_AXI_INTC_0_BASEADDR 0x41200000
#define XPAR_AXI_INTC_0_HIGHADDR 0x4120ffff
#define XPAR_AXI_INTC_0_KIND_OF_INTR 0x0
#define XPAR_AXI_INTC_0_IS_FAST 0x0
#define XPAR_AXI_INTC_0_IVAR_RST_VAL 0x10
#define XPAR_AXI_INTC_0_NUM_INTR_INPUTS 0x3
#define XPAR_AXI_INTC_0_ADDR_WIDTH 0x20
#define XPAR_AXI_INTC_0_OPTIONS 0x0
#define XPAR_AXI_INTC_0_INTCTYPE 0x0
#define XPAR_AXI_INTC_0_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral AXI_INTC_0 */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x0
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x0
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x3
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_0_BASEADDR 0x41c00000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41c0ffff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_AXI_TIMER_0_INTERRUPTS 0x2002
#define XPAR_FABRIC_AXI_TIMER_0_INTR 2
#define XPAR_AXI_TIMER_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c00000
#define XPAR_FABRIC_XTMRCTR_0_INTR 2
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c0ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_XTMRCTR_0_INTERRUPTS 0x2002
#define XPAR_XTMRCTR_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/*  BOARD definition */
#define XPS_BOARD_GENESYS2

#define XPAR_MIG_0_BASEADDRESS 0x80000000
#define XPAR_MIG_0_HIGHADDRESS 0xbfffffff
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

#define STDOUT_BASEADDRESS 0x40600000
#define STDIN_BASEADDRESS 0x40600000

/* Device ID */
#define XPAR_DEVICE_ID "7k325t"

#endif  /* end of protection macro */