domain_path: /home/asanche4/Master/nanoupv2025/vitis_Urbana_2024_1_analog/platform_microblaze/export/platform_microblaze/sw/standalone_microblaze_0
app_src_dir: /cad/adi/apps/xilinx/vivado/2024.1/Vitis/2024.1/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
